### PR TITLE
Make BlockEntities readable from schematic

### PR DESCRIPTION
**Pull request by sciner**
This data need for getting chest contents and etc.

### CODE REVIEW

**Comment by rom1504** [comment]
is this really enough to implement it ? can you add a test ?

**Comment by sciner** [comment]
yes, realy need. because in current version i cant get chest content without my fix

**Comment by sciner** [comment]
This fix doesn't need a test, it just adds another property and doesn't do anything complicated.

**Comment by rom1504** [comment]
please re-open if you want to finish it

**Pull request closed without merging**
